//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyBangDia2Entities : DbContext
    {
        public QuanLyBangDia2Entities()
            : base("name=QuanLyBangDia2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBangDia> tblBangDias { get; set; }
        public virtual DbSet<tblChiTietPhieuThue> tblChiTietPhieuThues { get; set; }
        public virtual DbSet<tblKhachHang> tblKhachHangs { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanViens { get; set; }
        public virtual DbSet<tblPhieuThue> tblPhieuThues { get; set; }
        public virtual DbSet<tblTheThanhVien> tblTheThanhViens { get; set; }
    
        public virtual ObjectResult<getBlackList_Result> getBlackList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getBlackList_Result>("getBlackList");
        }
    
        public virtual ObjectResult<getReportTongDoanhThu_Result> getReportTongDoanhThu(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> todate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReportTongDoanhThu_Result>("getReportTongDoanhThu", fromDateParameter, todateParameter);
        }
    
        public virtual ObjectResult<getTop5BangDiaYeuThich_Result> getTop5BangDiaYeuThich(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> todate, Nullable<int> top)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            var topParameter = top.HasValue ?
                new ObjectParameter("Top", top) :
                new ObjectParameter("Top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTop5BangDiaYeuThich_Result>("getTop5BangDiaYeuThich", fromDateParameter, todateParameter, topParameter);
        }
    }
}
