//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietPhieuThue
    {
        public string maPhieuThue { get; set; }
        public string maBangDia { get; set; }
        public Nullable<int> soLuongThue { get; set; }
        public Nullable<int> soNgayThue { get; set; }
        public Nullable<int> soLuongDaTra { get; set; }
    
        public virtual tblBangDia tblBangDia { get; set; }
        public virtual tblPhieuThue tblPhieuThue { get; set; }
    }
}
