//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyBangDiaEntities1 : DbContext
    {
        public QuanLyBangDiaEntities1()
            : base("name=QuanLyBangDiaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBangDia> tblBangDias { get; set; }
        public virtual DbSet<tblChiTietPhieuThue> tblChiTietPhieuThues { get; set; }
        public virtual DbSet<tblKhachHang> tblKhachHangs { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanViens { get; set; }
        public virtual DbSet<tblPhieuThue> tblPhieuThues { get; set; }
        public virtual DbSet<tblTheThanhVien> tblTheThanhViens { get; set; }
    }
}
