//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metro
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBangDia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBangDia()
        {
            this.tblChiTietPhieuThues = new HashSet<tblChiTietPhieuThue>();
        }
    
        public string maBangDia { get; set; }
        public string tenBangDia { get; set; }
        public string theLoai { get; set; }
        public string nhaSanXuat { get; set; }
        public Nullable<int> soLuongTon { get; set; }
        public string tinhTrang { get; set; }
        public Nullable<double> donGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietPhieuThue> tblChiTietPhieuThues { get; set; }
    }
}
