#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyBangDia")]
	public partial class DataQuanLyBangDiaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblBangDia(tblBangDia instance);
    partial void UpdatetblBangDia(tblBangDia instance);
    partial void DeletetblBangDia(tblBangDia instance);
    partial void InserttblChiTietPhieuThue(tblChiTietPhieuThue instance);
    partial void UpdatetblChiTietPhieuThue(tblChiTietPhieuThue instance);
    partial void DeletetblChiTietPhieuThue(tblChiTietPhieuThue instance);
    partial void InserttblKhachHang(tblKhachHang instance);
    partial void UpdatetblKhachHang(tblKhachHang instance);
    partial void DeletetblKhachHang(tblKhachHang instance);
    partial void InserttblNhanVien(tblNhanVien instance);
    partial void UpdatetblNhanVien(tblNhanVien instance);
    partial void DeletetblNhanVien(tblNhanVien instance);
    partial void InserttblPhieuThue(tblPhieuThue instance);
    partial void UpdatetblPhieuThue(tblPhieuThue instance);
    partial void DeletetblPhieuThue(tblPhieuThue instance);
    partial void InserttblTheThanhVien(tblTheThanhVien instance);
    partial void UpdatetblTheThanhVien(tblTheThanhVien instance);
    partial void DeletetblTheThanhVien(tblTheThanhVien instance);
    #endregion
		
		public DataQuanLyBangDiaDataContext() : 
				base(global::DAL.Properties.Settings.Default.QuanLyBangDiaConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyBangDiaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyBangDiaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyBangDiaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyBangDiaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblBangDia> tblBangDias
		{
			get
			{
				return this.GetTable<tblBangDia>();
			}
		}
		
		public System.Data.Linq.Table<tblChiTietPhieuThue> tblChiTietPhieuThues
		{
			get
			{
				return this.GetTable<tblChiTietPhieuThue>();
			}
		}
		
		public System.Data.Linq.Table<tblKhachHang> tblKhachHangs
		{
			get
			{
				return this.GetTable<tblKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<tblNhanVien> tblNhanViens
		{
			get
			{
				return this.GetTable<tblNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tblPhieuThue> tblPhieuThues
		{
			get
			{
				return this.GetTable<tblPhieuThue>();
			}
		}
		
		public System.Data.Linq.Table<tblTheThanhVien> tblTheThanhViens
		{
			get
			{
				return this.GetTable<tblTheThanhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBangDia")]
	public partial class tblBangDia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maBangDia;
		
		private string _tenBangDia;
		
		private string _theLoai;
		
		private string _nhaSanXuat;
		
		private System.Nullable<int> _soLuongTon;
		
		private string _tinhTrang;
		
		private System.Nullable<double> _donGia;
		
		private EntitySet<tblChiTietPhieuThue> _tblChiTietPhieuThues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaBangDiaChanging(string value);
    partial void OnmaBangDiaChanged();
    partial void OntenBangDiaChanging(string value);
    partial void OntenBangDiaChanged();
    partial void OntheLoaiChanging(string value);
    partial void OntheLoaiChanged();
    partial void OnnhaSanXuatChanging(string value);
    partial void OnnhaSanXuatChanged();
    partial void OnsoLuongTonChanging(System.Nullable<int> value);
    partial void OnsoLuongTonChanged();
    partial void OntinhTrangChanging(string value);
    partial void OntinhTrangChanged();
    partial void OndonGiaChanging(System.Nullable<double> value);
    partial void OndonGiaChanged();
    #endregion
		
		public tblBangDia()
		{
			this._tblChiTietPhieuThues = new EntitySet<tblChiTietPhieuThue>(new Action<tblChiTietPhieuThue>(this.attach_tblChiTietPhieuThues), new Action<tblChiTietPhieuThue>(this.detach_tblChiTietPhieuThues));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBangDia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maBangDia
		{
			get
			{
				return this._maBangDia;
			}
			set
			{
				if ((this._maBangDia != value))
				{
					this.OnmaBangDiaChanging(value);
					this.SendPropertyChanging();
					this._maBangDia = value;
					this.SendPropertyChanged("maBangDia");
					this.OnmaBangDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenBangDia", DbType="NVarChar(50)")]
		public string tenBangDia
		{
			get
			{
				return this._tenBangDia;
			}
			set
			{
				if ((this._tenBangDia != value))
				{
					this.OntenBangDiaChanging(value);
					this.SendPropertyChanging();
					this._tenBangDia = value;
					this.SendPropertyChanged("tenBangDia");
					this.OntenBangDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_theLoai", DbType="NVarChar(50)")]
		public string theLoai
		{
			get
			{
				return this._theLoai;
			}
			set
			{
				if ((this._theLoai != value))
				{
					this.OntheLoaiChanging(value);
					this.SendPropertyChanging();
					this._theLoai = value;
					this.SendPropertyChanged("theLoai");
					this.OntheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaSanXuat", DbType="NVarChar(50)")]
		public string nhaSanXuat
		{
			get
			{
				return this._nhaSanXuat;
			}
			set
			{
				if ((this._nhaSanXuat != value))
				{
					this.OnnhaSanXuatChanging(value);
					this.SendPropertyChanging();
					this._nhaSanXuat = value;
					this.SendPropertyChanged("nhaSanXuat");
					this.OnnhaSanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongTon", DbType="Int")]
		public System.Nullable<int> soLuongTon
		{
			get
			{
				return this._soLuongTon;
			}
			set
			{
				if ((this._soLuongTon != value))
				{
					this.OnsoLuongTonChanging(value);
					this.SendPropertyChanging();
					this._soLuongTon = value;
					this.SendPropertyChanged("soLuongTon");
					this.OnsoLuongTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhTrang", DbType="NVarChar(50)")]
		public string tinhTrang
		{
			get
			{
				return this._tinhTrang;
			}
			set
			{
				if ((this._tinhTrang != value))
				{
					this.OntinhTrangChanging(value);
					this.SendPropertyChanging();
					this._tinhTrang = value;
					this.SendPropertyChanged("tinhTrang");
					this.OntinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Float")]
		public System.Nullable<double> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBangDia_tblChiTietPhieuThue", Storage="_tblChiTietPhieuThues", ThisKey="maBangDia", OtherKey="maBangDia")]
		public EntitySet<tblChiTietPhieuThue> tblChiTietPhieuThues
		{
			get
			{
				return this._tblChiTietPhieuThues;
			}
			set
			{
				this._tblChiTietPhieuThues.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietPhieuThues(tblChiTietPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tblBangDia = this;
		}
		
		private void detach_tblChiTietPhieuThues(tblChiTietPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tblBangDia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChiTietPhieuThue")]
	public partial class tblChiTietPhieuThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPhieuThue;
		
		private string _maBangDia;
		
		private System.Nullable<int> _soLuongThue;
		
		private System.Nullable<int> _soNgayThue;
		
		private System.Nullable<int> _soLuongDaTra;
		
		private EntityRef<tblBangDia> _tblBangDia;
		
		private EntityRef<tblPhieuThue> _tblPhieuThue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhieuThueChanging(string value);
    partial void OnmaPhieuThueChanged();
    partial void OnmaBangDiaChanging(string value);
    partial void OnmaBangDiaChanged();
    partial void OnsoLuongThueChanging(System.Nullable<int> value);
    partial void OnsoLuongThueChanged();
    partial void OnsoNgayThueChanging(System.Nullable<int> value);
    partial void OnsoNgayThueChanged();
    partial void OnsoLuongDaTraChanging(System.Nullable<int> value);
    partial void OnsoLuongDaTraChanged();
    #endregion
		
		public tblChiTietPhieuThue()
		{
			this._tblBangDia = default(EntityRef<tblBangDia>);
			this._tblPhieuThue = default(EntityRef<tblPhieuThue>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieuThue", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhieuThue
		{
			get
			{
				return this._maPhieuThue;
			}
			set
			{
				if ((this._maPhieuThue != value))
				{
					if (this._tblPhieuThue.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhieuThueChanging(value);
					this.SendPropertyChanging();
					this._maPhieuThue = value;
					this.SendPropertyChanged("maPhieuThue");
					this.OnmaPhieuThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBangDia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maBangDia
		{
			get
			{
				return this._maBangDia;
			}
			set
			{
				if ((this._maBangDia != value))
				{
					if (this._tblBangDia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaBangDiaChanging(value);
					this.SendPropertyChanging();
					this._maBangDia = value;
					this.SendPropertyChanged("maBangDia");
					this.OnmaBangDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongThue", DbType="Int")]
		public System.Nullable<int> soLuongThue
		{
			get
			{
				return this._soLuongThue;
			}
			set
			{
				if ((this._soLuongThue != value))
				{
					this.OnsoLuongThueChanging(value);
					this.SendPropertyChanging();
					this._soLuongThue = value;
					this.SendPropertyChanged("soLuongThue");
					this.OnsoLuongThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNgayThue", DbType="Int")]
		public System.Nullable<int> soNgayThue
		{
			get
			{
				return this._soNgayThue;
			}
			set
			{
				if ((this._soNgayThue != value))
				{
					this.OnsoNgayThueChanging(value);
					this.SendPropertyChanging();
					this._soNgayThue = value;
					this.SendPropertyChanged("soNgayThue");
					this.OnsoNgayThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongDaTra", DbType="Int")]
		public System.Nullable<int> soLuongDaTra
		{
			get
			{
				return this._soLuongDaTra;
			}
			set
			{
				if ((this._soLuongDaTra != value))
				{
					this.OnsoLuongDaTraChanging(value);
					this.SendPropertyChanging();
					this._soLuongDaTra = value;
					this.SendPropertyChanged("soLuongDaTra");
					this.OnsoLuongDaTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBangDia_tblChiTietPhieuThue", Storage="_tblBangDia", ThisKey="maBangDia", OtherKey="maBangDia", IsForeignKey=true)]
		public tblBangDia tblBangDia
		{
			get
			{
				return this._tblBangDia.Entity;
			}
			set
			{
				tblBangDia previousValue = this._tblBangDia.Entity;
				if (((previousValue != value) 
							|| (this._tblBangDia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblBangDia.Entity = null;
						previousValue.tblChiTietPhieuThues.Remove(this);
					}
					this._tblBangDia.Entity = value;
					if ((value != null))
					{
						value.tblChiTietPhieuThues.Add(this);
						this._maBangDia = value.maBangDia;
					}
					else
					{
						this._maBangDia = default(string);
					}
					this.SendPropertyChanged("tblBangDia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhieuThue_tblChiTietPhieuThue", Storage="_tblPhieuThue", ThisKey="maPhieuThue", OtherKey="maPhieuThue", IsForeignKey=true)]
		public tblPhieuThue tblPhieuThue
		{
			get
			{
				return this._tblPhieuThue.Entity;
			}
			set
			{
				tblPhieuThue previousValue = this._tblPhieuThue.Entity;
				if (((previousValue != value) 
							|| (this._tblPhieuThue.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPhieuThue.Entity = null;
						previousValue.tblChiTietPhieuThues.Remove(this);
					}
					this._tblPhieuThue.Entity = value;
					if ((value != null))
					{
						value.tblChiTietPhieuThues.Add(this);
						this._maPhieuThue = value.maPhieuThue;
					}
					else
					{
						this._maPhieuThue = default(string);
					}
					this.SendPropertyChanged("tblPhieuThue");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKhachHang")]
	public partial class tblKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKH;
		
		private string _tenKH;
		
		private string _gioiTinh;
		
		private string _diaChi;
		
		private string _soDienThoai;
		
		private string _soCMND;
		
		private EntitySet<tblTheThanhVien> _tblTheThanhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OntenKHChanging(string value);
    partial void OntenKHChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OnsoCMNDChanging(string value);
    partial void OnsoCMNDChanged();
    #endregion
		
		public tblKhachHang()
		{
			this._tblTheThanhViens = new EntitySet<tblTheThanhVien>(new Action<tblTheThanhVien>(this.attach_tblTheThanhViens), new Action<tblTheThanhVien>(this.detach_tblTheThanhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKH", DbType="NVarChar(50)")]
		public string tenKH
		{
			get
			{
				return this._tenKH;
			}
			set
			{
				if ((this._tenKH != value))
				{
					this.OntenKHChanging(value);
					this.SendPropertyChanging();
					this._tenKH = value;
					this.SendPropertyChanged("tenKH");
					this.OntenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(10)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NVarChar(50)")]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCMND", DbType="NVarChar(50)")]
		public string soCMND
		{
			get
			{
				return this._soCMND;
			}
			set
			{
				if ((this._soCMND != value))
				{
					this.OnsoCMNDChanging(value);
					this.SendPropertyChanging();
					this._soCMND = value;
					this.SendPropertyChanged("soCMND");
					this.OnsoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhachHang_tblTheThanhVien", Storage="_tblTheThanhViens", ThisKey="maKH", OtherKey="maKH")]
		public EntitySet<tblTheThanhVien> tblTheThanhViens
		{
			get
			{
				return this._tblTheThanhViens;
			}
			set
			{
				this._tblTheThanhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblTheThanhViens(tblTheThanhVien entity)
		{
			this.SendPropertyChanging();
			entity.tblKhachHang = this;
		}
		
		private void detach_tblTheThanhViens(tblTheThanhVien entity)
		{
			this.SendPropertyChanging();
			entity.tblKhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhanVien")]
	public partial class tblNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private string _soCMND;
		
		private string _gioiTinh;
		
		private string _diaChi;
		
		private string _soDienThoai;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _taiKhoan;
		
		private string _matKhau;
		
		private string _avatar;
		
		private System.Nullable<bool> _trangThai;
		
		private EntitySet<tblPhieuThue> _tblPhieuThues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OntenNhanVienChanging(string value);
    partial void OntenNhanVienChanged();
    partial void OnsoCMNDChanging(string value);
    partial void OnsoCMNDChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OntaiKhoanChanging(string value);
    partial void OntaiKhoanChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    partial void OntrangThaiChanging(System.Nullable<bool> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public tblNhanVien()
		{
			this._tblPhieuThues = new EntitySet<tblPhieuThue>(new Action<tblPhieuThue>(this.attach_tblPhieuThues), new Action<tblPhieuThue>(this.detach_tblPhieuThues));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(50)")]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this.OntenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._tenNhanVien = value;
					this.SendPropertyChanged("tenNhanVien");
					this.OntenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCMND", DbType="NVarChar(50)")]
		public string soCMND
		{
			get
			{
				return this._soCMND;
			}
			set
			{
				if ((this._soCMND != value))
				{
					this.OnsoCMNDChanging(value);
					this.SendPropertyChanging();
					this._soCMND = value;
					this.SendPropertyChanged("soCMND");
					this.OnsoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(10)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NVarChar(50)")]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taiKhoan", DbType="NVarChar(50)")]
		public string taiKhoan
		{
			get
			{
				return this._taiKhoan;
			}
			set
			{
				if ((this._taiKhoan != value))
				{
					this.OntaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._taiKhoan = value;
					this.SendPropertyChanged("taiKhoan");
					this.OntaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NVarChar(50)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(200)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Bit")]
		public System.Nullable<bool> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblPhieuThue", Storage="_tblPhieuThues", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<tblPhieuThue> tblPhieuThues
		{
			get
			{
				return this._tblPhieuThues;
			}
			set
			{
				this._tblPhieuThues.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPhieuThues(tblPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = this;
		}
		
		private void detach_tblPhieuThues(tblPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhieuThue")]
	public partial class tblPhieuThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maThe;
		
		private string _maPhieuThue;
		
		private string _maNhanVien;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private System.Nullable<decimal> _thanhTien;
		
		private EntitySet<tblChiTietPhieuThue> _tblChiTietPhieuThues;
		
		private EntityRef<tblNhanVien> _tblNhanVien;
		
		private EntityRef<tblTheThanhVien> _tblTheThanhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTheChanging(string value);
    partial void OnmaTheChanged();
    partial void OnmaPhieuThueChanging(string value);
    partial void OnmaPhieuThueChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OnngayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapChanged();
    partial void OnthanhTienChanging(System.Nullable<decimal> value);
    partial void OnthanhTienChanged();
    #endregion
		
		public tblPhieuThue()
		{
			this._tblChiTietPhieuThues = new EntitySet<tblChiTietPhieuThue>(new Action<tblChiTietPhieuThue>(this.attach_tblChiTietPhieuThues), new Action<tblChiTietPhieuThue>(this.detach_tblChiTietPhieuThues));
			this._tblNhanVien = default(EntityRef<tblNhanVien>);
			this._tblTheThanhVien = default(EntityRef<tblTheThanhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maThe
		{
			get
			{
				return this._maThe;
			}
			set
			{
				if ((this._maThe != value))
				{
					if (this._tblTheThanhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaTheChanging(value);
					this.SendPropertyChanging();
					this._maThe = value;
					this.SendPropertyChanged("maThe");
					this.OnmaTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieuThue", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhieuThue
		{
			get
			{
				return this._maPhieuThue;
			}
			set
			{
				if ((this._maPhieuThue != value))
				{
					this.OnmaPhieuThueChanging(value);
					this.SendPropertyChanging();
					this._maPhieuThue = value;
					this.SendPropertyChanged("maPhieuThue");
					this.OnmaPhieuThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._tblNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTien", DbType="Money")]
		public System.Nullable<decimal> thanhTien
		{
			get
			{
				return this._thanhTien;
			}
			set
			{
				if ((this._thanhTien != value))
				{
					this.OnthanhTienChanging(value);
					this.SendPropertyChanging();
					this._thanhTien = value;
					this.SendPropertyChanged("thanhTien");
					this.OnthanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhieuThue_tblChiTietPhieuThue", Storage="_tblChiTietPhieuThues", ThisKey="maPhieuThue", OtherKey="maPhieuThue")]
		public EntitySet<tblChiTietPhieuThue> tblChiTietPhieuThues
		{
			get
			{
				return this._tblChiTietPhieuThues;
			}
			set
			{
				this._tblChiTietPhieuThues.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblPhieuThue", Storage="_tblNhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public tblNhanVien tblNhanVien
		{
			get
			{
				return this._tblNhanVien.Entity;
			}
			set
			{
				tblNhanVien previousValue = this._tblNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVien.Entity = null;
						previousValue.tblPhieuThues.Remove(this);
					}
					this._tblNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblPhieuThues.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("tblNhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTheThanhVien_tblPhieuThue", Storage="_tblTheThanhVien", ThisKey="maThe", OtherKey="maThe", IsForeignKey=true)]
		public tblTheThanhVien tblTheThanhVien
		{
			get
			{
				return this._tblTheThanhVien.Entity;
			}
			set
			{
				tblTheThanhVien previousValue = this._tblTheThanhVien.Entity;
				if (((previousValue != value) 
							|| (this._tblTheThanhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTheThanhVien.Entity = null;
						previousValue.tblPhieuThues.Remove(this);
					}
					this._tblTheThanhVien.Entity = value;
					if ((value != null))
					{
						value.tblPhieuThues.Add(this);
						this._maThe = value.maThe;
					}
					else
					{
						this._maThe = default(string);
					}
					this.SendPropertyChanged("tblTheThanhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietPhieuThues(tblChiTietPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tblPhieuThue = this;
		}
		
		private void detach_tblChiTietPhieuThues(tblChiTietPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tblPhieuThue = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTheThanhVien")]
	public partial class tblTheThanhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maThe;
		
		private string _maKH;
		
		private System.Nullable<System.DateTime> _ngayHetHan;
		
		private System.Nullable<System.DateTime> _ngayCap;
		
		private EntitySet<tblPhieuThue> _tblPhieuThues;
		
		private EntityRef<tblKhachHang> _tblKhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTheChanging(string value);
    partial void OnmaTheChanged();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OnngayHetHanChanging(System.Nullable<System.DateTime> value);
    partial void OnngayHetHanChanged();
    partial void OnngayCapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayCapChanged();
    #endregion
		
		public tblTheThanhVien()
		{
			this._tblPhieuThues = new EntitySet<tblPhieuThue>(new Action<tblPhieuThue>(this.attach_tblPhieuThues), new Action<tblPhieuThue>(this.detach_tblPhieuThues));
			this._tblKhachHang = default(EntityRef<tblKhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThe", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maThe
		{
			get
			{
				return this._maThe;
			}
			set
			{
				if ((this._maThe != value))
				{
					this.OnmaTheChanging(value);
					this.SendPropertyChanging();
					this._maThe = value;
					this.SendPropertyChanged("maThe");
					this.OnmaTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._tblKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayHetHan", DbType="Date")]
		public System.Nullable<System.DateTime> ngayHetHan
		{
			get
			{
				return this._ngayHetHan;
			}
			set
			{
				if ((this._ngayHetHan != value))
				{
					this.OnngayHetHanChanging(value);
					this.SendPropertyChanging();
					this._ngayHetHan = value;
					this.SendPropertyChanged("ngayHetHan");
					this.OnngayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayCap", DbType="Date")]
		public System.Nullable<System.DateTime> ngayCap
		{
			get
			{
				return this._ngayCap;
			}
			set
			{
				if ((this._ngayCap != value))
				{
					this.OnngayCapChanging(value);
					this.SendPropertyChanging();
					this._ngayCap = value;
					this.SendPropertyChanged("ngayCap");
					this.OnngayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTheThanhVien_tblPhieuThue", Storage="_tblPhieuThues", ThisKey="maThe", OtherKey="maThe")]
		public EntitySet<tblPhieuThue> tblPhieuThues
		{
			get
			{
				return this._tblPhieuThues;
			}
			set
			{
				this._tblPhieuThues.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhachHang_tblTheThanhVien", Storage="_tblKhachHang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true)]
		public tblKhachHang tblKhachHang
		{
			get
			{
				return this._tblKhachHang.Entity;
			}
			set
			{
				tblKhachHang previousValue = this._tblKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tblKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKhachHang.Entity = null;
						previousValue.tblTheThanhViens.Remove(this);
					}
					this._tblKhachHang.Entity = value;
					if ((value != null))
					{
						value.tblTheThanhViens.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(string);
					}
					this.SendPropertyChanged("tblKhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPhieuThues(tblPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tblTheThanhVien = this;
		}
		
		private void detach_tblPhieuThues(tblPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tblTheThanhVien = null;
		}
	}
}
#pragma warning restore 1591
